# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build_tests_and_deploy_Python_app_to_Azure_Web_App

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'backend/users-module/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend/users-module

    steps:
      - name: Check repo
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and start virtual environment with env
        run: |
          make buildenv
          source venv/bin/activate
      
      - name: Install dependencies
        run: make installlibs
      

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Tests with Pytest
        run: pytest -vv --junit-xml=test-results.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: ./backend/users-module/test-results.xml


      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: users-api
          path: | 
            ./backend/users-module/
            !venv/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: users-api
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sistema-mgm-service-users'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_79B9F8D590334A18A949728ADC39D539 }}
