
name: Build_java_and_frontend_Docker_images_and_push_to_DockerHub

on:
  push:
    branches: [dzarkV]
  # pull_request:
  #   types: [opened]
  #   branches: [main]
  workflow_dispatch:

env:
  IMAGE__JAVA_NAME: inventorybe
  IMAGE__FRONTEND_NAME: inventoryfe

jobs:
  image-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend/proyectoGinnaMarcela

    steps:
      - name: Check repo
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: |
          pwd
          ls -la
          mvn install -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE__JAVA_NAME }}:v0.0.3

  image-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Check repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE__FRONTEND_NAME }}:v0.0.1

