# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sistema-mgm-service-users

on:
  push:
    branches:
      - dzarkV
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: ./backend/users-module
        run: |
          make buildenv
          source venv/bin/activate
      # echo 'export MONGO_DETAILS=${{ secrets.MONGO_DETAILS }}' >> venv/bin/activate
      # echo 'export DB_NAME=usersMGM' >> venv/bin/activate
      # echo 'export COLLECTION_NAME=${{ secrets.COLLECTION_NAME }}' >> venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend/users-module
        run: make installlibs
          
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Tests with Pytest
      #   working-directory: ./backend/users-module
      #   run: |
      #     cd app/ && python -m pytest -vv
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: users-api
          path: |
            ./backend/users-module 
            !venv/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: users-api
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sistema-mgm-service-users'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_79B9F8D590334A18A949728ADC39D539 }}
